export const texts = [
  "Exploring new technologies and innovations is not just a hobby; it's a journey into the future, shaping our world.",
  "React's influence on front-end development is undeniable, offering a streamlined, efficient approach to user interface creation.",
  "Typing fast and accurately is not just about speed; it's about enhancing productivity and achieving excellence in every task.",
  "The transformative power of machine learning across industries is profound, offering insights and efficiencies previously unimaginable.",
  "Blockchain technology is not just a buzzword; it's a revolution in security and trust, promising to redefine how we transact.",
  "The future of power is sustainable energy solutions, which are not only vital for our planet but also for our survival.",
  "Virtual reality offers more than just entertainment; it brings immersive experiences that have the potential to change how we learn and interact.",
  "Quantum computing is on the brink of revolutionizing our computational capabilities, promising speeds we've never seen before.",
  "Artificial intelligence is reshaping our world, offering solutions and challenges in equal measure, transforming every sector it touches.",
  "The rise of digital currencies is changing the financial landscape, challenging traditional banking and opening up new forms of investment.",
  "The shift to remote work is not just a temporary change but a new norm that's redefining professional and personal boundaries.",
  "In our digital age, cybersecurity measures are not optional; they are crucial for safeguarding our personal and professional lives.",
  "Cloud computing's offer of flexibility and scalability is transforming how businesses operate, making technology accessible to all.",
  "Augmented reality is blending the digital and physical worlds in ways that enhance our experiences and challenge our perceptions.",
  "Big data analytics is not just about handling large volumes of data; it's about driving decisions that shape the future of businesses.",
  "The Internet of Things is connecting everyday objects, creating a seamlessly integrated network that enhances our lives in countless ways.",
  "The development of autonomous vehicles is not just about technology; it's about paving the way for a new era of smart, sustainable mobility.",
  "Renewable energy sources are more than alternatives; they are the cornerstone of a sustainable and viable environmental strategy.",
  "Genetic editing offers the potential to transform medicine, opening up possibilities for treating diseases previously considered untreatable.",
  "Space exploration is more than a quest for knowledge; it's a testament to human ingenuity and the unquenchable thirst for discovery.",
];
